server:
  port: 4666
spring:
  datasource:

    url: jdbc:mysql://localhost:3306/todo?useSSL=false
    username: root
    password: Password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

